# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Aug 16 23:32:51 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 428)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gbTarjeta = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.gbTarjeta.setFont(font)
        self.gbTarjeta.setObjectName("gbTarjeta")
        self.gridTarjeta = QtGui.QGridLayout(self.gbTarjeta)
        self.gridTarjeta.setObjectName("gridTarjeta")
        self.tePalabra = QtGui.QTextEdit(self.gbTarjeta)
        self.tePalabra.setObjectName("tePalabra")
        self.gridTarjeta.addWidget(self.tePalabra, 0, 0, 1, 2)
        self.pbEditarTarjeta = QtGui.QPushButton(self.gbTarjeta)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pbEditarTarjeta.setFont(font)
        self.pbEditarTarjeta.setObjectName("pbEditarTarjeta")
        self.gridTarjeta.addWidget(self.pbEditarTarjeta, 1, 0, 1, 1)
        self.pbSiguiente = QtGui.QPushButton(self.gbTarjeta)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pbSiguiente.setFont(font)
        self.pbSiguiente.setObjectName("pbSiguiente")
        self.gridTarjeta.addWidget(self.pbSiguiente, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.gbTarjeta, 0, 0, 1, 1)
        self.gbTiempo = QtGui.QGroupBox(self.centralwidget)
        self.gbTiempo.setObjectName("gbTiempo")
        self.gridTiempo = QtGui.QGridLayout(self.gbTiempo)
        self.gridTiempo.setObjectName("gridTiempo")
        self.lcdTiempo = QtGui.QLCDNumber(self.gbTiempo)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lcdTiempo.setFont(font)
        self.lcdTiempo.setNumDigits(3)
        self.lcdTiempo.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdTiempo.setProperty("intValue", 60)
        self.lcdTiempo.setObjectName("lcdTiempo")
        self.gridTiempo.addWidget(self.lcdTiempo, 0, 0, 1, 1)
        self.pbIniciarTiempo = QtGui.QPushButton(self.gbTiempo)
        self.pbIniciarTiempo.setObjectName("pbIniciarTiempo")
        self.gridTiempo.addWidget(self.pbIniciarTiempo, 1, 0, 1, 1)
        self.pbPausarTiempo = QtGui.QPushButton(self.gbTiempo)
        self.pbPausarTiempo.setObjectName("pbPausarTiempo")
        self.gridTiempo.addWidget(self.pbPausarTiempo, 2, 0, 1, 1)
        self.pbResetearTiempo = QtGui.QPushButton(self.gbTiempo)
        self.pbResetearTiempo.setObjectName("pbResetearTiempo")
        self.gridTiempo.addWidget(self.pbResetearTiempo, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbTiempo, 0, 1, 1, 1)
        self.gbGrupos = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.gbGrupos.setFont(font)
        self.gbGrupos.setObjectName("gbGrupos")
        self.gridGrupos = QtGui.QGridLayout(self.gbGrupos)
        self.gridGrupos.setObjectName("gridGrupos")
        self.grupoA = QtGui.QGroupBox(self.gbGrupos)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.grupoA.setFont(font)
        self.grupoA.setAlignment(QtCore.Qt.AlignCenter)
        self.grupoA.setObjectName("grupoA")
        self.gridLayout_3 = QtGui.QGridLayout(self.grupoA)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.grupoA)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lcdPuntajeA = QtGui.QLCDNumber(self.grupoA)
        self.lcdPuntajeA.setNumDigits(3)
        self.lcdPuntajeA.setObjectName("lcdPuntajeA")
        self.gridLayout_3.addWidget(self.lcdPuntajeA, 0, 1, 1, 1)
        self.pbSumarA = QtGui.QPushButton(self.grupoA)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pbSumarA.setFont(font)
        self.pbSumarA.setObjectName("pbSumarA")
        self.gridLayout_3.addWidget(self.pbSumarA, 1, 0, 1, 2)
        self.gridGrupos.addWidget(self.grupoA, 0, 0, 1, 1)
        self.grupoB = QtGui.QGroupBox(self.gbGrupos)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.grupoB.setFont(font)
        self.grupoB.setAlignment(QtCore.Qt.AlignCenter)
        self.grupoB.setFlat(False)
        self.grupoB.setCheckable(False)
        self.grupoB.setObjectName("grupoB")
        self.gridLayout_4 = QtGui.QGridLayout(self.grupoB)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lcdPuntajeB = QtGui.QLCDNumber(self.grupoB)
        self.lcdPuntajeB.setFrameShape(QtGui.QFrame.Box)
        self.lcdPuntajeB.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdPuntajeB.setNumDigits(3)
        self.lcdPuntajeB.setObjectName("lcdPuntajeB")
        self.gridLayout_4.addWidget(self.lcdPuntajeB, 0, 1, 1, 1)
        self.pbSumarB = QtGui.QPushButton(self.grupoB)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pbSumarB.setFont(font)
        self.pbSumarB.setObjectName("pbSumarB")
        self.gridLayout_4.addWidget(self.pbSumarB, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.grupoB)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridGrupos.addWidget(self.grupoB, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.gbGrupos, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 23))
        self.menubar.setObjectName("menubar")
        self.menu_Archivo = QtGui.QMenu(self.menubar)
        self.menu_Archivo.setObjectName("menu_Archivo")
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuevo_Juego = QtGui.QAction(MainWindow)
        self.actionNuevo_Juego.setObjectName("actionNuevo_Juego")
        self.action_Salir = QtGui.QAction(MainWindow)
        self.action_Salir.setObjectName("action_Salir")
        self.actionInstrucciones = QtGui.QAction(MainWindow)
        self.actionInstrucciones.setObjectName("actionInstrucciones")
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.actionNuevo_Juego)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.action_Salir)
        self.menuAyuda.addAction(self.actionInstrucciones)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Taboo Words!", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTarjeta.setTitle(QtGui.QApplication.translate("MainWindow", "Tarjeta", None, QtGui.QApplication.UnicodeUTF8))
        self.pbEditarTarjeta.setText(QtGui.QApplication.translate("MainWindow", "Editar Tarjeta", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSiguiente.setText(QtGui.QApplication.translate("MainWindow", "Siguiente", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTiempo.setTitle(QtGui.QApplication.translate("MainWindow", "Tiempo de Juego", None, QtGui.QApplication.UnicodeUTF8))
        self.pbIniciarTiempo.setText(QtGui.QApplication.translate("MainWindow", "Iniciar!", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPausarTiempo.setText(QtGui.QApplication.translate("MainWindow", "Pausar", None, QtGui.QApplication.UnicodeUTF8))
        self.pbResetearTiempo.setText(QtGui.QApplication.translate("MainWindow", "Resetear", None, QtGui.QApplication.UnicodeUTF8))
        self.gbGrupos.setTitle(QtGui.QApplication.translate("MainWindow", "Grupos", None, QtGui.QApplication.UnicodeUTF8))
        self.grupoA.setTitle(QtGui.QApplication.translate("MainWindow", "Grupo A", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Puntaje:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSumarA.setText(QtGui.QApplication.translate("MainWindow", "Sumar Punto", None, QtGui.QApplication.UnicodeUTF8))
        self.grupoB.setTitle(QtGui.QApplication.translate("MainWindow", "Grupo B", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSumarB.setText(QtGui.QApplication.translate("MainWindow", "Sumar Punto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Puntaje:", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Archivo.setTitle(QtGui.QApplication.translate("MainWindow", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNuevo_Juego.setText(QtGui.QApplication.translate("MainWindow", "Nuevo Juego", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Salir.setText(QtGui.QApplication.translate("MainWindow", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInstrucciones.setText(QtGui.QApplication.translate("MainWindow", "Como Jugar?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainWindow", "Acerca de...", None, QtGui.QApplication.UnicodeUTF8))

